# These are supported funding model platforms

github: Nirj2004
Paytm: 7439005838356@paytm
BHIM-UPI: 7439005838@upi
Phone-Pe: biswas.nirjhar2@ybl
MobiKwik: 7439005838@ikwik
Google-Pay: nirjharbiswas2004-2@okhdfcbank
ICICI-iMobile-Pay: 7439005838@icici
Tata-Pay: 7439005838@tapicici
